name: Check and build

on: push

env:
  ENVIRONMENT: dev

jobs:
  webapp_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Setup dependencies
        run: npx playwright install --with-deps

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:run && yarn e2e:run

      - name: Build App
        run: yarn build:${{ env.ENVIRONMENT }}

      - name: Build Storybook
        run: sudo yarn storybook:build # running sudo here because of permissions issues

      - name: Deploy App
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish dist --project-name react-tech-stack

      - name: Deploy Storybook
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish storybook-static --project-name react-tech-stack-storybook
